# This file was generated by GoReleaser. DO NOT EDIT.
class SlideServe < Formula
  desc "small presentation and dev server for simple slides, based on https://github.com/trikita/slide-html"
  homepage "https://github.com/cdreier/slide-serve"
  url "https://github.com/mpas/slide-serve-fork/releases/download/v0.1-rc1/slide-serve_0.1-rc1_Darwin_x86_64.tar.gz"
  version "0.1-rc1"
  sha256 "24c82d310e8e04bb7f50ca0685b8348632f1178ab7579cc59c3ade5d720bf24a"

  def install
    bin.install "slide-serve"
  end
end
