# This file was generated by GoReleaser. DO NOT EDIT.
class SlideServe < Formula
  desc "small presentation and dev server for simple slides, based on https://github.com/trikita/slide-html"
  homepage "https://github.com/cdreier/slide-serve"
  url "https://github.com/mpas/slide-serve-fork/releases/download/v0.1-rc1/slide-serve_0.1-rc1_Darwin_x86_64.tar.gz"
  version "0.1-rc1"
  sha256 "6c95ff5a780f686b4c803a574d211935e73ee0e6fdae29fdf46d59e6b4608a56"

  def install
    bin.install "slide-serve"
  end
end
